the vignette of the expp package is broken because of the as.data.frame.table method
see https://travis-ci.org/yihui/crandalf/builds/37020408

previously, kable() will turn an object of class "table" of 2 x 2 to a data.frame of 4 x 3, which will lead to

  Error: length of 'dimnames' [2] not equal to array extent